### ISSUE TITLE
When will the dataset be made public? 

### ISSUE THREAD

**Issue by sam-zyzhang** [luxiya01/mbes-registration-data#1]
Dear authors, 

Since there are very few publicly available datasets for underwater sonar point clouds, when can the data be released for more in-depth research?

Thank you.

**Comment by luxiya01** [comment]
Hi, thank you for your interest in this work! I've just got back from vacation and will release the next week :)

**Comment by ishani-narwankar** [comment]
Wanted to follow up on this, was the dataset released?

**Comment by luxiya01** [comment]
Sorry for the delay, the data is now available :)

**Comment by ishani-narwankar** [comment]
Thank you so much!
